application: level2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
 - url: /static
  static_dir: static
 - url: /.*
  script: level2.app

libraries:
 - name: webapp2
  version: "2.5.2"
 - name: Jinja2
  version: "1.1.1"